# Copyright (c) 2015 Jean Dias

development:
  adapter: postgresql
  encoding: unicode
  database: bloginitial_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: bloginitial_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: bloginitial_production
  pool: 5
  username: 
  password: 
  host: localhost
  port: 5432
